---
name: Devenv Issue
description: Report an issue with the development environment setup
labels: ["area/devenv", "needs-triage"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to report an issue with the Codespaces devenv!

      We really appreciate the community efforts to improve the ngrok Kubernetes Operator.
- type: textarea
  attributes:
    label: Description
    description: A description of the issue
- type: textarea
  attributes:
    label: Related issues
    description: Are there any related issues?
- type: markdown
  attributes:
    value: "Thank you for help in improving the ngrok Kubernetes Operator!"
